version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: doirp-app

  # Для разработки можно добавить nginx для проксирования
  dev-nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx-dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    profiles:
      - dev
